name: P-Bit FE Build Deployment Workflow

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build-image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "dckr_pat_zCbQbfMN3WfwpQWRvkSPceTHC4Q" | docker login -u "powarsteam" --password-stdin

      - name: Build Docker Image
        run: docker build -t powarsteam/pbit-fe:latest .

      - name: Push Docker Image to Docker Hub
        run: docker push powarsteam/pbit-fe:latest

  deploy-to-dev:
    name: Deploy to Development Environment
    runs-on: ubuntu-latest
    needs: build-image  # depends on the previous job finishing successfully

    steps:
      - name: SSH into Linode and deploy Docker container
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 172.233.114.136
          username: powarsteam
          key: ${{ secrets.SSH_KEY }}
          port: 5823
          script: |
            echo "Deploying P-Bit backend..."

            # Stop and remove any old containers if they exist
            docker stop pbit-fe || true
            docker rm pbit-fe || true

            # Clean up unused images
            docker image prune -f || true

            # Pull the latest image from Docker Hub
            docker pull powarsteam/pbit-fe:latest

            # Run the new container with the same configuration as before
            docker run -d \
            --name pbit-fe \
            --restart always \
            -p 80:80 \
            powarsteam/pbit-fe:latest

            echo "✅ Deployment completed successfully!"
